services:
  postgres-db:
    image: postgres
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: timewise
      POSTGRES_USER: su
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d


volumes:
  postgres-data:

