name: Deploy Application

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build Project and run tests
        run: mvn clean install
      - name: Login Docker Hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t cavasini/appointment_service .
      - name: Push image docker
        run: docker push cavasini/appointment_service
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: target/site/jacoco/jacoco.xml
          fail_ci_if_error: true

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull new image from docker hub
        run: docker pull cavasini/appointment_service:latest

      - name: Stop container if exists
        run: |
          if [ "$(docker ps -aq -f name=deploy_appointment)" ]; then
          docker stop deploy_appointment
          fi

      - name: Remove container if exists
        run: |
          if [ "$(docker ps -aq -f name=deploy_appointment)" ]; then
          docker rm deploy_appointment
          fi

      - name: Run docker container
        run: docker run -d -p 8080:8080 --name deploy_appointment cavasini/appointment_service




